application: fastsunday
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /
  script: home.app
